tap "homebrew/bundle"
tap "homebrew/cask", "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask.git"
tap "homebrew/core", "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
tap "homebrew/services"
tap "martido/graph"
brew "aria2"
brew "autoconf"
brew "libpng"
brew "direnv"
brew "enchant"
brew "git"
brew "git-lfs"
brew "gnupg", link: false
brew "go"
brew "nginx"
brew "node"
brew "pandoc"
brew "polipo", restart_service: true
brew "postgresql@10", restart_service: true, link: true
brew "telnet"
brew "thefuck"
brew "tree"
brew "wget"
brew "zlib"
cask "android-platform-tools"
cask "gpg-suite"
cask "xquartz"
