[project]
# PEP 621 project metadata
# See https://www.python.org/dev/peps/pep-0621/
dependencies = [
    "pipx~=0.16",
    "virtualenv~=20.4",
    "pip~=21.0",
    "naipyext[be]~=0.7",
]


[tool]
[tool.pdm]
